export class products {
  all = [
    {
      id: 1,
      name: 'iPhone 14',
      price: 999,
      brand: 'Apple',
      image: [
        'https://images.olx.com.pk/thumbnails/529914997-800x600.webp',
        'https://images.olx.com.pk/thumbnails/529914998-800x600.webp',
        'https://images.olx.com.pk/thumbnails/529914999-800x600.webp',
        'https://images.olx.com.pk/thumbnails/529915000-800x600.webp',
      ],
      totalImages: 4,
      location: 'New York',
      description: 'Latest iPhone model with A15 chip and 5G support.',
      details:
        'The iPhone 14 features a stunning Super Retina XDR display, advanced camera system, and powerful A15 Bionic chip for lightning-fast performance. With 5G support, you can enjoy ultra-fast download speeds and improved connectivity. The device also includes enhanced battery life and a sleek design that fits comfortably in your hand.',
      condition: 'New',
      category: 'Smartphones',
      mainCategory: 'Mobiles',
      features: [
        '6.1-inch Super Retina XDR display',
        'A15 Bionic chip with 5G support',
        'Dual 12MP camera system with Night mode',
        'Ceramic Shield front cover for durability',
        'Face ID for secure authentication',
        'MagSafe technology for easy accessory attachment',
        'iOS 15 with new features and improvements',
        'Water and dust resistance (IP68)',
        'Available in multiple colors',
        'Storage options: 128GB, 256GB, 512GB',
        'Battery life: Up to 17 hours of talk time',
        'Fast charging and wireless charging support',
        '5G capable for faster download speeds',
        'Siri voice assistant for hands-free control',
        'Apple Pay for secure payments',
        'iCloud integration for seamless data backup',
        'AirDrop for easy file sharing',
      ],
      sizes: ['128GB', '256GB', '512GB'],
    },
    {
      id: 2,
      name: 'Samsung Galaxy S21',
      price: 799,
      brand: 'Samsung',
      image: [
        'https://images.olx.com.pk/thumbnails/533889313-800x600.webp',
        'https://images.olx.com.pk/thumbnails/533889314-800x600.webp',
      ],
      location: 'Los Angeles',
      description: 'High-end smartphone with excellent camera and performance.',
      details:
        'The Samsung Galaxy S21 features a stunning Dynamic AMOLED display, powerful Exynos 2100 processor, and an impressive camera system with multiple lenses for versatile photography. With 5G connectivity, you can enjoy fast download speeds and seamless streaming. The device also includes a sleek design, long-lasting battery, and enhanced security features.',
      condition: 'New',
      category: 'Smartphones',
      mainCategory: 'Mobiles',
      features: [
        '6.2-inch Dynamic AMOLED 2X display',
        'Exynos 2100 processor with 5G support',
        'Triple camera system with 64MP telephoto lens',
        'Corning Gorilla Glass Victus for durability',
        'In-display fingerprint scanner for secure authentication',
        'One UI 3.1 with new features and improvements',
        'Water and dust resistance (IP68)',
        'Available in multiple colors',
        'Storage options: 128GB, 256GB',
        'Battery life: Up to 18 hours of talk time',
        'Fast charging and wireless charging support',
        'S Pen support for enhanced productivity',
        'Samsung DeX for desktop experience',
        'Samsung Pay for secure payments',
        'Bixby voice assistant for hands-free control',
        'iCloud integration for seamless data backup',
      ],
      sizes: ['128GB', '256GB'],
    },
    {
      id: 3,
      name: 'Google Pixel 6',
      price: 699,
      brand: 'Google',
      image: [
        'https://images.olx.com.pk/thumbnails/533912220-800x600.webp',
        'https://images.olx.com.pk/thumbnails/533912221-800x600.webp',
        'https://images.olx.com.pk/thumbnails/533912222-800x600.webp',
      ],
      location: 'Chicago',
      description: 'Smartphone with stock Android experience and great camera.',
      details:
        'The Google Pixel 6 features a stunning OLED display, powerful Google Tensor chip, and an advanced camera system with AI enhancements for stunning photos. With stock Android experience, you can enjoy a clean and intuitive interface with regular updates. The device also includes 5G support, long-lasting battery life, and enhanced security features.',
      condition: 'New',
      category: 'Smartphones',
      mainCategory: 'Mobiles',
      features: [
        '6.4-inch OLED display',
        'Google Tensor chip with 5G support',
        'Dual camera system with 50MP wide lens',
        'Corning Gorilla Glass Victus for durability',
        'In-display fingerprint scanner for secure authentication',
        'Stock Android experience with regular updates',
        'Water and dust resistance (IP68)',
        'Available in multiple colors',
        'Storage options: 128GB, 256GB',
        'Battery life: Up to 24 hours of talk time',
        'Fast charging and wireless charging support',
        'Google Assistant for hands-free control',
        'Google Photos with unlimited storage for photos and videos',
        'Titan M security chip for enhanced security',
        'Live Translate for real-time translation',
      ],
      sizes: ['128GB', '256GB'],
    },
    {
      id: 4,
      name: 'OnePlus 9',
      price: 649,
      brand: 'OnePlus',
      image: ['https://images.olx.com.pk/thumbnails/533893577-800x600.webp',
        'https://images.olx.com.pk/thumbnails/533893578-800x600.webp',
        'https://images.olx.com.pk/thumbnails/533893579-800x600.webp'
      ],
      location: 'Houston',
      description:
        'Flagship smartphone with fast charging and smooth performance.',
      details:
        'The OnePlus 9 features a stunning Fluid AMOLED display, powerful Snapdragon 888 processor, and an advanced camera system co-developed with Hasselblad for exceptional photography. With Warp Charge technology, you can enjoy ultra-fast charging speeds. The device also includes 5G support, OxygenOS for a smooth user experience, and a sleek design that stands out.',
      condition: 'New',
      category: 'Smartphones',
      mainCategory: 'Mobiles',
      features: [
        '6.55-inch Fluid AMOLED display',
        'Snapdragon 888 processor with 5G support',
        'Triple camera system with 48MP wide lens',
        'Corning Gorilla Glass for durability',
        'In-display fingerprint scanner for secure authentication',
        'OxygenOS with new features and improvements',
        'Water and dust resistance (IP68)',
        'Available in multiple colors',
        'Storage options: 128GB, 256GB',
        'Battery life: Up to 20 hours of talk time',
        'Fast charging and wireless charging support',
        'Dual stereo speakers for immersive audio',
        'Gaming mode for enhanced performance',
        'OnePlus Buds compatibility for seamless audio experience',
      ],
      sizes: ['128GB', '256GB'],
    },
    {
      id: 5,
      name: 'Xiaomi Mi 11',
      price: 599,
      brand: 'Xiaomi',
      image: ['https://images.olx.com.pk/thumbnails/533887476-800x600.webp',
        'https://images.olx.com.pk/thumbnails/533887477-800x600.webp',
        'https://images.olx.com.pk/thumbnails/533887478-800x600.webp',
        'https://images.olx.com.pk/thumbnails/533887479-800x600.webp',
        'https://images.olx.com.pk/thumbnails/533887480-800x600.webp',
        'https://images.olx.com.pk/thumbnails/533887481-800x600.webp',
        'https://images.olx.com.pk/thumbnails/533887482-800x600.webp',
      ],
      location: 'Phoenix',
      description: 'Affordable flagship with great performance and camera.',
      details:
        'The Xiaomi Mi 11 features a stunning AMOLED display, powerful Snapdragon 888 processor, and an advanced camera system for exceptional photography. With 5G support, you can enjoy fast download speeds and seamless streaming. The device also includes a sleek design, long-lasting battery, and MIUI for a customizable user experience.',
      condition: 'New',
      category: 'Smartphones',
      mainCategory: 'Mobiles',
      features: [
        '6.81-inch AMOLED display',
        'Snapdragon 888 processor with 5G support',
        'Triple camera system with 108MP wide lens',
        'Corning Gorilla Glass Victus for durability',
        'In-display fingerprint scanner for secure authentication',
        'MIUI with new features and improvements',
        'Water and dust resistance (IP68)',
        'Available in multiple colors',
        'Storage options: 128GB, 256GB',
        'Battery life: Up to 18 hours of talk time',
        'Fast charging and wireless charging support',
        'Dual stereo speakers for immersive audio',
        'Gaming mode for enhanced performance',
      ],
      sizes: ['128GB', '256GB'],
    },
    {
      id: 6,
      name: 'Sony Xperia 1 III',
      price: 1299,
      brand: 'Sony',
      image: ['https://images.olx.com.pk/thumbnails/522528150-800x600.webp',
      ],
      location: 'Philadelphia',
      description:
        'Premium smartphone with 4K display and advanced camera features.',
      details:
        'The Sony Xperia 1 III features a stunning 4K HDR OLED display, powerful Snapdragon 888 processor, and an advanced camera system with real-time eye autofocus for exceptional photography. With 5G support, you can enjoy fast download speeds and seamless streaming. The device also includes a sleek design, long-lasting battery, and unique features for content creators.',
      condition: 'New',
      category: 'Smartphones',
      mainCategory: 'Mobiles',
      features: [
        '6.5-inch 4K HDR OLED display',
        'Snapdragon 888 processor with 5G support',
        'Triple camera system with 12MP wide lens',
        'Corning Gorilla Glass Victus for durability',
        'In-display fingerprint scanner for secure authentication',
        'Sony Camera Pro app for advanced photography features',
        'Water and dust resistance (IP65/IP68)',
        'Available in multiple colors',
        'Storage options: 256GB, 512GB',
        'Battery life: Up to 20 hours of talk time',
        'Fast charging and wireless charging support',
        'Dual stereo speakers for immersive audio',
        'Gaming mode for enhanced performance',
      ],
      sizes: ['256GB', '512GB'],
    },
    {
      id: 7,
      name: 'Nokia G50',
      price: 299,
      brand: 'Nokia',
      image:
        ['https://www.notebookcheck.net/fileadmin/_processed_/5/3/csm_4_zu_3_Nokia_G50_ffb64d053d.jpg',
        
        ],
      location: 'San Antonio',
      description: 'Budget smartphone with good battery life and performance.',
      details:
        'The Nokia G50 features a large HD+ display, powerful Snapdragon 480 processor, and a long-lasting battery for all-day usage. With 5G support, you can enjoy fast download speeds and seamless streaming. The device also includes a clean Android experience with regular updates, durable design, and enhanced security features.',
      condition: 'New',
      category: 'Smartphones',
      mainCategory: 'Mobiles',
      features: [
        '6.82-inch HD+ display',
        'Snapdragon 480 processor with 5G support',
        'Triple camera system with 48MP wide lens',
        'Corning Gorilla Glass for durability',
        'Side-mounted fingerprint scanner for secure authentication',
        'Stock Android experience with regular updates',
        'Water and dust resistance (IP68)',
        'Available in multiple colors',
        'Storage options: 64GB, 128GB',
        'Battery life: Up to 30 hours of talk time',
        'Fast charging support',
        'Dual stereo speakers for immersive audio',
      ],
      sizes: ['64GB', '128GB'],
    },
    {
      id: 8,
      name: 'Motorola Edge 20',
      price: 499,
      brand: 'Motorola',
      image: ['https://images.olx.com.pk/thumbnails/533150149-800x600.webp',
        'https://images.olx.com.pk/thumbnails/533150150-800x600.webp',
        'https://images.olx.com.pk/thumbnails/533150151-800x600.webp',
        'https://images.olx.com.pk/thumbnails/533150152-800x600.webp',
        'https://images.olx.com.pk/thumbnails/533150153-800x600.webp',
        'https://images.olx.com.pk/thumbnails/533150154-800x600.webp',
        'https://images.olx.com.pk/thumbnails/533150155-800x600.webp',
        'https://images.olx.com.pk/thumbnails/533150156-800x600.webp',
        'https://images.olx.com.pk/thumbnails/533150157-800x600.webp',
        'https://images.olx.com.pk/thumbnails/533150158-800x600.webp',
        'https://images.olx.com.pk/thumbnails/533150159-800x600.webp',
        'https://images.olx.com.pk/thumbnails/533150160-800x600.webp',
        'https://images.olx.com.pk/thumbnails/533150161-800x600.webp',
        'https://images.olx.com.pk/thumbnails/533150162-800x600.webp',
        'https://images.olx.com.pk/thumbnails/533150163-800x600.webp',
        'https://images.olx.com.pk/thumbnails/533150164-800x600.webp',
        'https://images.olx.com.pk/thumbnails/533150165-800x600.webp',
        'https://images.olx.com.pk/thumbnails/533150166-800x600.webp',
        'https://images.olx.com.pk/thumbnails/533150167-800x600.webp',
      ],
      location: 'San Diego',
      description: 'Mid-range smartphone with good performance and camera.',
      details:
        'The Motorola Edge 20 features a stunning OLED display, powerful Snapdragon 778G processor, and an advanced camera system for exceptional photography. With 5G support, you can enjoy fast download speeds and seamless streaming. The device also includes a sleek design, long-lasting battery, and My UX for a customizable user experience.',
      condition: 'New',
      category: 'Smartphones',
      mainCategory: 'Mobiles',
      features: [
        '6.7-inch OLED display',
        'Snapdragon 778G processor with 5G support',
        'Triple camera system with 108MP wide lens',
        'Corning Gorilla Glass Victus for durability',
        'In-display fingerprint scanner for secure authentication',
        'My UX with new features and improvements',
        'Water and dust resistance (IP68)',
        'Available in multiple colors',
        'Storage options: 128GB, 256GB',
        'Battery life: Up to 24 hours of talk time',
        'Fast charging and wireless charging support',
        'Dual stereo speakers for immersive audio',
      ],
      sizes: ['128GB', '256GB'],
    },
    {
      id: 9,
      name: 'Yamaha YZF-R3',
      price: 4999,
      brand: 'Yamaha',
      image: ['https://images.olx.com.pk/thumbnails/532291800-800x600.webp',
        'https://images.olx.com.pk/thumbnails/532291801-800x600.webp',
        'https://images.olx.com.pk/thumbnails/532291802-800x600.webp',
        'https://images.olx.com.pk/thumbnails/532291803-800x600.webp',        
      ],
      location: 'New York',
      description:
        'Sportbike with a powerful engine and agile handling for thrilling rides.',
      details:
        'The Yamaha YZF-R3 features a powerful 321cc engine, lightweight chassis, and aggressive styling for an exhilarating riding experience. With advanced suspension and braking systems, you can enjoy precise handling and control on the road. The bike also includes modern technology, comfortable seating position, and sporty design that stands out.',
      condition: 'New',
      category: 'Motorcycles',
      mainCategory: 'Bikes',
      features: [
        '321cc liquid-cooled, inline twin engine',
        '6-speed transmission for smooth shifting',
        'Aggressive R-series styling and aerodynamic design',
        'Advanced suspension with adjustable front forks',
        'Dual-channel ABS for enhanced braking performance',
        'Lightweight chassis for agile handling',
        'Full LED lighting for improved visibility',
        'Digital LCD instrument panel with multiple functions',
        'Sporty riding position for enhanced control',
        'Available in multiple colors and graphics options',
      ],
      sizes: ['321cc'],
    },
    {
      id: 10,
      name: 'Kawasaki Ninja 400',
      price: 5999,
      brand: 'Kawasaki',
      image: ['https://images.olx.com.pk/thumbnails/531244582-800x600.webp',
        'https://images.olx.com.pk/thumbnails/531244583-800x600.webp',
        'https://images.olx.com.pk/thumbnails/531244584-800x600.webp',
        'https://images.olx.com.pk/thumbnails/531244585-800x600.webp',
        'https://images.olx.com.pk/thumbnails/531244586-800x600.webp',
      ],
      location: 'Los Angeles',
      description:
        'Lightweight sportbike with impressive performance and style.',
      details:
        'The Kawasaki Ninja 400 features a powerful 399cc engine, lightweight chassis, and aggressive styling for an exhilarating riding experience. With advanced suspension and braking systems, you can enjoy precise handling and control on the road. The bike also includes modern technology, comfortable seating position, and sporty design that stands out.',
      condition: 'New',
      category: 'Motorcycles',
      mainCategory: 'Bikes',
      features: [
        '399cc liquid-cooled, parallel twin engine',
        '6-speed transmission for smooth shifting',
        'Aggressive Ninja styling and aerodynamic design',
        'Advanced suspension with adjustable front forks',
        'Dual-channel ABS for enhanced braking performance',
        'Lightweight chassis for agile handling',
        'Full LED lighting for improved visibility',
        'Digital LCD instrument panel with multiple functions',
        'Sporty riding position for enhanced control',
        'Available in multiple colors and graphics options',
      ],
      sizes: ['399cc'],
    },
    {
      id: 11,
      name: 'Honda CB500F',
      price: 6999,
      brand: 'Honda',
      image:
        ['https://on-track.in/wp-content/uploads/2022/11/Honda-CB500F-1024x681.jpg',

        ],
      location: 'Chicago',
      description:
        'Naked bike with a comfortable riding position and versatile performance.',
      details:
        'The Honda CB500F features a powerful 471cc engine, lightweight chassis, and naked styling for a comfortable riding experience. With advanced suspension and braking systems, you can enjoy precise handling and control on the road. The bike also includes modern technology, comfortable seating position, and versatile design that suits various riding styles.',
      condition: 'New',
      category: 'Motorcycles',
      mainCategory: 'Bikes',
      features: [
        '471cc liquid-cooled, parallel twin engine',
        '6-speed transmission for smooth shifting',
        'Naked styling with aggressive design',
        'Advanced suspension with adjustable front forks',
        'Dual-channel ABS for enhanced braking performance',
        'Lightweight chassis for agile handling',
        'Full LED lighting for improved visibility',
        'Digital LCD instrument panel with multiple functions',
        'Comfortable riding position for long-distance rides',
        'Available in multiple colors and graphics options',
      ],
      sizes: ['471cc'],
    },
    {
      id: 12,
      name: 'Ducati Monster 821',
      price: 8999,
      brand: 'Ducati',
      image:
        ['https://www.cnet.com/a/img/resize/912d1a95a3d6059332a0635bc2222c6e17d17c2b/hub/2020/11/23/80e8a9e4-aa39-4158-8c03-d36739a21a4a/ducati-monster-821-stealth-037.jpg?auto=webp&width=1200',],
      location: 'Houston',
      description:
        'Iconic naked bike with a powerful engine and aggressive styling.',
      details:
        'The Ducati Monster 821 features a powerful 821cc engine, lightweight chassis, and iconic naked styling for an exhilarating riding experience. With advanced suspension and braking systems, you can enjoy precise handling and control on the road. The bike also includes modern technology, comfortable seating position, and sporty design that stands out.',
      condition: 'New',
      category: 'Motorcycles',
      mainCategory: 'Bikes',
      features: [
        '821cc liquid-cooled, L-twin engine',
        '6-speed transmission for smooth shifting',
        'Iconic Monster styling with aggressive design',
        'Advanced suspension with adjustable front forks',
        'Dual-channel ABS for enhanced braking performance',
        'Lightweight chassis for agile handling',
        'Full LED lighting for improved visibility',
        'Digital LCD instrument panel with multiple functions',
        'Sporty riding position for enhanced control',
        'Available in multiple colors and graphics options',
      ],
      sizes: ['821cc'],
    },
    {
      id: 13,
      name: 'BMW R1250GS',
      price: 15999,
      brand: 'BMW',
      image:
        ['https://media.zigcdn.com/media/content/2018/Sep/p90322917_highres_bmw-r-1250-gs-hp-09-.jpg',],
      location: 'Phoenix',
      description:
        'Adventure touring bike with advanced technology and long-distance comfort.',
      details:
        'The BMW R1250GS features a powerful 1254cc engine, advanced suspension, and touring capabilities for long-distance rides. With modern technology, including ride modes and connectivity features, you can enjoy a comfortable and versatile riding experience. The bike also includes a rugged design, comfortable seating position, and advanced safety features for peace of mind on the road.',
      condition: 'New',
      category: 'Motorcycles',
      mainCategory: 'Bikes',
      features: [
        '1254cc liquid-cooled, boxer engine',
        '6-speed transmission for smooth shifting',
        'Adventure touring styling with rugged design',
        'Advanced suspension with adjustable front forks',
        'Dual-channel ABS for enhanced braking performance',
        'Lightweight chassis for agile handling',
        'Full LED lighting for improved visibility',
        'Digital LCD instrument panel with multiple functions',
        'Comfortable riding position for long-distance rides',
        'Available in multiple colors and graphics options',
      ],
      sizes: ['1254cc'],
    },
    {
      id: 14,
      name: 'Harley-Davidson Street 750',
      price: 7999,
      brand: 'Harley-Davidson',
      image:
        ['https://s1.cdn.autoevolution.com/images/moto_gallery/HARLEY-DAVIDSON-Street-750-7172_3.jpg',],
      location: 'Philadelphia',
      description:
        'Cruiser motorcycle with a classic design and comfortable riding position.',
      details:
        'The Harley-Davidson Street 750 features a powerful 749cc engine, classic cruiser styling, and comfortable seating position for relaxed rides. With modern technology, including ABS and security features, you can enjoy a safe and enjoyable riding experience. The bike also includes a rugged design, customizable options, and iconic Harley-Davidson branding that stands out.',
      condition: 'New',
      category: 'Motorcycles',
      mainCategory: 'Bikes',
      features: [
        '749cc liquid-cooled, V-twin engine',
        '6-speed transmission for smooth shifting',
        'Cruiser styling with classic design',
        'Advanced suspension with adjustable front forks',
        'Dual-channel ABS for enhanced braking performance',
        'Lightweight chassis for agile handling',
        'Full LED lighting for improved visibility',
        'Digital LCD instrument panel with multiple functions',
        'Comfortable riding position for long-distance rides',
        'Available in multiple colors and graphics options',
      ],
      sizes: ['749cc'],
    },
    
  ];
}
